### PR TITLE
Updated rails, rspec cucumber testcase

### PR DESCRIPTION
**Pull request by narutosanjiv**

### CODE REVIEW

**Comment by narutosanjiv** [comment]
@alexandrz  In rspec, Travis getting API rate limit exceeded for 173.247.96.10.

**Comment by narutosanjiv** [comment]
@alexandrz What happened?. I do not get any response from you.

**Comment by narutosanjiv** [comment]
If this pull request merge , i wanted to update tip4commit bootstrap ui to bootstrap latest  as well.

**Comment by alexandrz** [comment]
I would merge it, but the build is still failing:

```Failing Scenarios:

cucumber features/find_project.feature:47 # Scenario: Projects owned by an organization should show project avatar```

Also, it would be great to squash at least duplicate commits.

**Comment by narutosanjiv** [comment]
Failing spec say "GET https://api.github.com/repos/tip4commit/tip4commit?client_id=111111111111&client_secret=(redacted): 403 - API rate limit exceeded for 173.247.96.10"

**Comment by narutosanjiv** [comment]
I will squash all commit into one, & will send you pull request tomorrow.

**Comment by narutosanjiv** [comment]
@alexandrz Now everything look fine. Sqash duplicate commits.

**Pull request merged**
