### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by ds009**
Add simplified chinese for the people's republic of China and traditional chinese for Hong Kong.

### CODE REVIEW

**Comment by alexandrz** [comment]
Hi, why have you closed the pull request? Sorry, I was not able to merge it before.

**Comment by ds009** [comment]
@alexandrz sorry, it hasn't been merged after long time, I thought there was something wrong, now it's reopened.

**Comment by ds009** [comment]
@alexandrz A test failed, but it's about finding a term 'sign in' in text? Is this test reasonable while people translate things into other languages? Please let me know if I committed some wrong code

**Comment by alexandrz** [comment]
Thank you for the translation! The issue is that you have not changed the root key of the locale files form `en` to `cn` and `hk`.

**Pull request merged**
