### PR TITLE
Add Indonesian translation for locale

### PR DESCRIPTION
**Pull request by rizkyekoputra**

### CODE REVIEW

**Comment by CB49** [comment]
At the top of the file, you should change `en` to `id`.

**Comment by rizkyekoputra** [comment]
ah, sorry, forgot to change, have pushed the new one

**Comment by CB49** [comment]
Seems like that fixed the build problem. Nice!

**Comment by alexandrz** [comment]
Thank you!

**Comment by rizkyekoputra** [comment]
@alexandrz no updating on this page anymore?? https://tip4commit.com/github/tip4commit/tip4commit

**Comment by alexandrz** [comment]
@rizkyekoputra it's being updated automatically. You used a different email to create this commits. Try to add `rizky.eko@elephanttalk.com` to your emails – https://github.com/settings/emails

**Comment by rizkyekoputra** [comment]
@alexandrz oh sorry, haha, will add that

**Comment by alexandrz** [comment]
@rizkyekoputra Now you can remove it back if you do not want to use it

**Comment by rizkyekoputra** [comment]
@alexandrz so no auto-updated on https://tip4commit.com/github/tip4commit/tip4commit?

**Comment by rizkyekoputra** [comment]
ok thanks @alexandrz

**Pull request merged**
